server:
  port: 8080

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB # 限制单个上传文件的最大大小为 10MB。如果上传的文件大小超过这个值，将会被拒绝上传。
      max-request-size: 10MB # 限制整个上传请求的最大大小为 10MB。这包括所有上传文件的大小之和。以下为解释：
  cache:
    redis:
      time-to-live: 300000 # 缓存默认过期时间，5分钟

logging:
  config: classpath:templates/logback-meblog.xml

jwt:
  issuer: { YOUR_NAME }
  secret: { JWT_SECRET }
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

# 网站域名配置
site:
  domain: { WEBSITE_DOMAIN }
  external-link-domain: { WEBSITE_DOMAIN }
